### ISSUE TITLE
$isVerified is annotated even if doctrine is configured to use attributes

### ISSUE THREAD

**Issue by Radiergummi** [SymfonyCasts/verify-email-bundle#100]
In more recent Symfony installations, it's recommended to use PHP attributes instead of docblock annotations. If a project is configured to use Doctrine attributes instead of annotations, the bundle should act accordingly; otherwise, the property will not be added to the database and accounts silently fail to be verified.

**Comment by jrushlow** [comment]
This has been fixed with the release of MakerBundle v1.37.0 https://github.com/symfony/maker-bundle/releases/tag/v1.37.0
