### ISSUE TITLE
Unable to change lifetime parameter

### ISSUE THREAD

**Issue by PaulSGit1** [SymfonyCasts/verify-email-bundle#114]
Hi there,

we are using your package and totally love it. It's easy and nice!

However, I struggle with the following:
I want to change the lifetime value and did everything as described.
I created a verify_email.yaml file in the given directory and used the following code inside it:

```yaml
symfonycasts_verify_email:
     lifetime: 86400
```

However, it is still stuck at 1 hour.

Did I miss something?

Thankful for any help! :)

**Comment by magali-thuaire** [comment]
Hello @PaulSGit1 

The same problem here, I cleared the cache in dev environment and now it works!
Hope it would help you

I love SymfonyCasts ❤️

**Comment by PaulSGit1** [comment]
Hi,

thanks a lot for the hint!

That fixed it.
Sorry for the issue then! 

Kind regards :)
