### ISSUE TITLE
I don't receive the email confirmation ,even though I login after that.Using Symfony 6 and gmail-mailer.

### ISSUE THREAD

**Issue by Serzhanov** [SymfonyCasts/verify-email-bundle#115]
Hello guys, I don't receive my email confirmation and I loggin after that (I am not sure if it should work like that). I was trying to identify where my problem with the internet and I got an interesting article about [that  ](https://serveanswer.com/questions/symfony-6-mailer-doesnt-send-email-verification-or-mailerinterface-too).It was written in Feb 2022 I think you ve already figured this issue or you haven't? Should I try to switch to Symfony 5 or there is a problem in my code?
Also, I don't see where Gmail has been used in code.

.env
```
###> symfony/google-mailer ###

MAILER_DSN=gmail://xxxxxxxx@default #with using URL encode 
###< symfony/google-mailer ###

```
RegistrationController.php
```
$this->emailVerifier->sendEmailConfirmation('app_verify_email', $user,
                (new TemplatedEmail())
                    ->from(new Address('ns490367@gmail.com', 'Nurbek'))
                    ->to($user->getEmail())
                    ->subject('Please Confirm your Email')
                    ->htmlTemplate('registration/confirmation_email.html.twig')
            );

return $userAuthenticator->authenticateUser(
                $user,
                $authenticator,
                $request
            );

```
EmailVerifier.php
```

 public function sendEmailConfirmation(string $verifyEmailRouteName, UserOriginal $user, TemplatedEmail $email): void
    {
        $signatureComponents = $this->verifyEmailHelper->generateSignature(
            $verifyEmailRouteName,
            $user->getId(),
            $user->getEmail(),
            ['id' => $user->getId()]
        );

        $context = $email->getContext();
        $context['signedUrl'] = $signatureComponents->getSignedUrl();
        $context['expiresAtMessageKey'] = $signatureComponents->getExpirationMessageKey();
        $context['expiresAtMessageData'] = $signatureComponents->getExpirationMessageData();

        $email->context($context);

        $this->mailer->send($email);

```

Sorry if I forgot something to mention, and thanks in advance.

**Comment by AlinePencreach** [comment]
Hello :)
Did you find the solution ? I'm in the same situation 🤔

**Comment by Serzhanov** [comment]
> Hello :) Did you find the solution ? I'm in the same situation 🤔

Unfortuanally I didn't,well I just quite this issue.But recently I was working with mail services in Symfony and my advice to you is just to generate a confirmation mail by MailInterface.
Good luck!

**Comment by florent6001** [comment]
Same problem for me after a fresh install of symfony 6.

**Comment by florent6001** [comment]
Finally found the problem, you got messenger installed on your symfony installation.
You have to remove there 3 lines from messenger.yaml if you don't want to use it for your email.
```php
Symfony\Component\Mailer\Messenger\SendEmailMessage: async
Symfony\Component\Notifier\Message\ChatMessage: async
Symfony\Component\Notifier\Message\SmsMessage: async
```

If you want to keep using it, you can start the messenger services in your local environment with this command:
```bash
php bin/console messenger:consume async
```

**Comment by jrushlow** [comment]
I actually just stumbled on this as well working on tests in MakerBundle for verify-email. The "problem" is indeed as @florent6001  mentioned above. See https://symfony.com/doc/current/mailer.html#creating-sending-messages for additional information on how to configure the mail client.
