### ISSUE TITLE
Document the lifetime option

### ISSUE THREAD

**Issue by weaverryan** [SymfonyCasts/verify-email-bundle#117]
Hi!

I realized, when someone asked me today, that we don't show the bundle's configuration options in the README. There is just one - lifetime - but probably we should have a config reference in the README.

Cheers!

**Comment by jrushlow** [comment]
the `lifetime` config option is the only configurable parameter we have isn't it?

**Comment by bocharsky-bw** [comment]
Yes, only one that is `lifetime`, and we already have it in the README, see: https://github.com/SymfonyCasts/verify-email-bundle#configuration

So, I'm closing it
