### ISSUE TITLE
[docs] Automatic authentication not working without first running make:auth

### ISSUE THREAD

**Issue by Frikkle** [SymfonyCasts/verify-email-bundle#126]
When running the `bin/console make:registration-form` command, the wizard asks whether you want the user to be automatically authenticated.

When not having used the MakerBundle's `make:auth` command (but implementing the `form_login` following the [symfony docs ](https://symfony.com/doc/current/security.html#form-login)), the command show that no guard authenticators are found, so it cannot enable this functionality. See message below.

![automatically_authenticate](https://user-images.githubusercontent.com/9324165/187041604-00229613-1970-4a67-b835-9cba621c5a9e.png)
 
Though this is related to the MakerBundle command (and a solution can be found by scouring their issue repository), it might be worth mentioning it here in the docs. Maybe adding a small section on "Enabling automatic authentication" stating that it only works when guard authenticators are present and/or that it can be fixed by having set-up the authentication system through `make:auth`.

Just a thought, maybe it helps others out that run into the same issue.

**Comment by jrushlow** [comment]
Thanks @Frikkle for bringing this up. I'll see about a) getting some more tests in maker bundle to cover this in the future && b) ensuring the "new" authentication system is fully supported w/ `make:registration-form` and automatic authentication.

**Comment by jrushlow** [comment]
This is finally been fixed with the release of `v1.56.0` https://github.com/symfony/maker-bundle/releases/tag/v1.56.0
