### ISSUE TITLE
One time use url

### ISSUE THREAD

**Issue by dchevilletRDR** [SymfonyCasts/verify-email-bundle#129]
Hi, 
I implement the bundle like this https://symfonycasts.com/screencast/symfony-security/verify-signed-url 

Then in my app, I log in the user just after check the url. 

But the link in the mail still work for log in after the check. I can add some custom control, but are they an option to do this in yaml config file ? 

Thanks

**Comment by jrushlow** [comment]
Howdy,

The verification url's should not explicitly log in a user. E.g. The user clicks a the link -> the app see's that the user is not logged in -> the app asks the user for his/her credentials -> the app then marks the user as having a verified email address.

It is possible to use Anonymous Validation that does not require users to be authenticated. Check out the docs in  https://github.com/SymfonyCasts/verify-email-bundle#anonymous-validation

I hope this helps, let us know if you have anymore questions!

**Comment by dchevilletRDR** [comment]
Hello,

Thanks for your answer. Ok its's more clear. I was wrong about the design. I fix it.
