### ISSUE TITLE
The controller for URI "/register" is not callable: Environment variable not found: "MAILER_DSN".

### ISSUE THREAD

**Issue by Ikari-421** [SymfonyCasts/verify-email-bundle#138]
Hi,
I am beginer with symfony and i had this error after install [verify-email-bundle]
I am using symfony 6 and Php 8.2
Anyone can help me ?
Thanks

**Comment by konateallaman** [comment]
In your .env file change the following, uncomment # MAILER_DSN=null://null  and modify it: 

###> symfony/mailer ###

MAILER_DSN=your_mail_provider://your_email:your password@localhost
###< symfony/mailer ###

**Comment by bocharsky-bw** [comment]
Thank you for this tip @konateallaman ! Really, it should help, you just need to configure your mailer that will send the actual verify email message.

I'm closing this now. Feel free to reopen if still have this error

**Comment by LaDetox87** [comment]
salut c'est bryan
