### ISSUE TITLE
Determine / Implement `CHANGELOG.md` strategy for `1.x` (main) && `2.x` to avoid merge conflicts when merging "up"

### ISSUE THREAD

**Issue by jrushlow** [SymfonyCasts/verify-email-bundle#162]
How should we handle the changelog going forward. e.g. `CHANGELOG-1.x.md` && `CHANGELOG-2.x.md`? I feel like keeping a single `CHANGELOG.md` will cause merge conflicts but I could be wrong.

This strategy would also apply to `reset-password-bundle` when it comes up for a version bump.

cc @weaverryan @bocharsky-bw

**Comment by weaverryan** [comment]
I see the problem... but I'm not sure it'll be so bad, as we won't be developing SO much in the older branches. I say we keep it simple with just `CHANGELOG.md` and deal with any conflicts. They should be easy to solve.

**Comment by jrushlow** [comment]
sounds good to me!
fixed in #173
