### ISSUE TITLE
inconsistent naming conventions in SignatureComponents

### ISSUE THREAD

**Issue by jrushlow** [SymfonyCasts/verify-email-bundle#2]
We're calling the property `uri` and the getter `getSignature()`

https://github.com/SymfonyCasts/verify-email-bundle/blob/master/src/Model/VerifyEmailSignatureComponents.php

**Comment by jrushlow** [comment]
- [ ]  Re-check all arg, var, method names again

**Comment by weaverryan** [comment]
Looks like this has been fixed - I like the new `getSignedUrl()` method name.
