### ISSUE TITLE
Time validation (unsafe)

### ISSUE THREAD

**Issue by carlinhus** [SymfonyCasts/verify-email-bundle#201]
I think using this validation is very unsafe:
```php
if ($request->query->getInt('expires') <= time()) {
    throw new ExpiredSignatureException();
}
```
Expiration timestamp must be saved on User's entity.

**Comment by carlinhus** [comment]
Hello @bocharsky-bw ,

It compares the querystring parameter called "expires" with actual timestamp. It can be changed manually by the user who is trying to verify the email.

So you can change manually the timestamp sent to the server.

Are you agree?

**Comment by carlinhus** [comment]
Yeah, I'm agree with you @bocharsky-bw 

I didn't take into account the signature. I'ts my bad.

Sorry about that.

I close this issue.

Have a nice day.

**Comment by bocharsky-bw** [comment]
No problem! Thanks for double-checking
