### ISSUE TITLE
Validation anonymously

### ISSUE THREAD

**Issue by AlexandrePetrone** [SymfonyCasts/verify-email-bundle#27]
If we don't login the user after registration it is impossible to validate the email.
It would have been interesting to be able to validate them also if the user is not logged in.

**Comment by jrushlow** [comment]
Howdy! Thanks for using our bundle! The short answer is yes, the long answer is no. I'll explain -

If you are using the MakerBundle `make:registration-form` the the user must be logged in before they can be verified. Security being the reasoning behind this decision. 

Fundamentally, if the user was not required to be logged in, where would you get the user's unique identifier & email address from? The `token` query param in the validation link, that was emailed to the user, is a one way hash comprised of the user id and email address. So the only way to validate that token is to recreate it. For example, we wouldn't want to allow a bot to validate an email address they don't have access to.

The long part of the answer is, the bundle itself doesn't care about logins, users, or anything else really. It just cares about a route name that it can use to get the route from the `Router`, a string that represents an identifier (user-id), and a string that represents the users email. The helper then gives you in return a url that has a hashed signature and token.

When you validate that URL, the bundle again only cares about the URL itself, the user identifier, and a email address... So in theory, if you are just using the bundle by itself, you can implement it within your app without a login system. That probably is not a very wise choice - but it is possible if you have some other means of obtaining the `id` & `email`.

I would post an example of the long answer above, but I don't want someone to come along and actually use it thinking it is "the right way"..

**Comment by AlexandrePetrone** [comment]
Thank you for your reply.
Indeed I use the bundle with the Make component
However, I find it surprising to connect the user once the registration has been completed before verifying the email.

I would have thought that the user registers then one sends him a message to validate his password and finally he can connect to the site.

**Comment by morgzz** [comment]
@AlexandrePetrone 

This allows you to log the user in after the user registers.

```php
namespace App\Controller;

use Symfony\Component\Security\Guard\GuardAuthenticatorHandler;
use App\Security\LoginFormAuthenticator;

class RegisterController extends AbstractController
{

    /**
     * @Route("/register", name="app_register")
     */
    public function register(
        //...
        GuardAuthenticatorHandler $guardHandler,
        LoginFormAuthenticator $authenticator
        //....
    ): Response
    {

        //....

        if ($form->isSubmitted() && $form->isValid()) {
        
            //....

            // generate a signed url and email it to the user
            $this->emailVerifier->sendEmailConfirmation('app_verify_email', $this->user,
                (new TemplatedEmail())
                    ->from(new Address('FROM-EMAIL-HERE', 'EMAIL-NAME'))
                    ->to()
                    ->subject('Please confirm your email!')
                    ->htmlTemplate('emails/registration/confirmation_email.html.twig')
                );
            // do anything else you need here, like send an email

            return $guardHandler->authenticateUserAndHandleSuccess(
                    $this->user,
                    $request,
                    $authenticator,
                    'main' // firewall name in security.yaml
                );
            }
        }

        return $this->render('registration/register.html.twig', [
            'registrationForm' => $form->createView(),
        ]);
    }
}
```

**Comment by AlexandrePetrone** [comment]
@morgzz 

Thanks but I know that.
I created the issue because I think it’s a shame to have to be connected to validate the email address.
For some websites or applications it is not relevant that at the end of the registration the user is automatically connected. 
Except that with this logic it is not possible to validate their email address, unless logged on site.
It would be preferable to store a token and the email address and during validation, checking that if the mail / token combination is identical to the database.

**Comment by residentcode** [comment]
> Thank you for your reply.
> Indeed I use the bundle with the Make component
> However, I find it surprising to connect the user once the registration has been completed before verifying the email.
> 
> I would have thought that the user registers then one sends him a message to validate his password and finally he can connect to the site.

you can simply add condition in **LoginFromAuthenticator.php** to prevent UnVerified user to login before Verifying his email,


`<pre>

public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        if ($targetPath = $this->getTargetPath($request->getSession(), $providerKey)) {
            return new RedirectResponse($targetPath);
        }
        // check if user has verified email
        $verified = $this->entityManager->getRepository(User::class)->findOneBy(['isVerified' => 1 ]);
       //Get user email address
        $email = $this->getCredentials($request);
    if ($verified){
        return new RedirectResponse($this->urlGenerator->generate('home'));

    }else{
            return new Response(
                '<html><body>Your email '.$email['email'].' has not been verified!: </body></html>'
            );
        }
    }


</pre>


`

**Comment by AlexandrePetrone** [comment]
Thank you for your response, however for the checks at the connection level it is preferable to use the [user checker].(https://symfony.com/doc/current/security/user_checkers.html)

However, the problem is linked to the validateEmailConfirmation method which attempts the connected user.

```php
    /**
     * Validate a signed an email confirmation request.
     *
     * If something is wrong with the email confirmation, a
     * VerifyEmailExceptionInterface will be thrown.
     *
     * The $userEmail should be the email address that the currently-authenticated
     * user is trying to get validated. This is usually the current user's
     * email address.
     *
     * In more a complex setup, where you allow a user to verify multiple
     * emails, this would be the email that the currently-authenticated user
     * is trying to validate. You may even store a user's many email addresses
     * (and whether or not each is verified) in another database table. In
     * that case, you would need to call this method with each unverified
     * email in that table (for the currently-authenticated user) to see if
     * the signature is valid for any of the email addresses. If you find the
     * one that is valid, you could then mark that email as "confirmed".
     *
     * @param string $signedUrl the signed URL, usually the current URL that the
     *                          user has just clicked in their email
     * @param string $userId    currently-authenticated user's unique identifier
     * @param string $userEmail currently-authenticated user's email, or, more specifically,
     *                          the email that the current user is attempting to validate
     *
     * @throws VerifyEmailExceptionInterface
     */
    public function validateEmailConfirmation(string $signedUrl, string $userId, string $userEmail): void;
```

**Comment by fr43nk** [comment]
Hi,
thank you for this interesting post. I came to same point by using this with a rest-api. With that it is also not possible to have a logged in session to get the user id to verify the token. Furthermore, this approach also requires the user to use the same browser when clicking the verification link as he/she did for registering. This is something that is not always true.
What is so insecure about having the email address or the userid in that verification link? Maybe you can add a configuration option to let me decide to have that email in the link or not.

Best regards

**Comment by MatTheCat** [comment]
> we wouldn't want to allow a bot to validate an email address they don't have access to.

What is the point of signing the token then?

**Comment by dsoriano** [comment]
Hi all,
unless I missed something, there is another problem with this behavior: if the user doesn't validate the email, he still can login and access a restricted area once logged. If I want to add security and reject a user which the email is not validated I have to
- Check in every restricted controller the email is validated. This is not a good solution imo
- Or set a new role if the email has been validated. Also not a solution: if a new role is added to the user, he's disconnected and must login again. So he has to login twice. Impossible.
- Or create a listener like AccessListener to secure a restricted area

All these solutions are, I think, not good, they add unnecessary complexity just to check that an email has been validated.

Regards

**Comment by jrushlow** [comment]
> if the user doesn't validate the email, he still can login and access a restricted area once logged.

This bundle provides the developer a means to validate a users email. As the requirements are different for every application - we leave it up to the developer to implement their own strategy for handling validated / invalidated users.

**Comment by MatTheCat** [comment]
This bundle provides the developer a means to validate a **logged** user’s email. Maybe it should be in the README because I don’t think it integrates in most workflows.

**Comment by dsoriano** [comment]
> This bundle provides the developer a means to validate a users email. As the requirements are different for every application - we leave it up to the developer to implement their own strategy for handling validated / invalidated users.

Yeah I understand that and you're right. What I mean is the choices made for this bundle let the developper in a uncomfortable position. All the time gained by using it is lost by the time passed to adapt the security properly. Just because of the choice to force the user to be logged to validate the email, it's impossible to use the common symfony security tools like roles.

**Comment by cristobal85** [comment]
I have the same problem. I try to check if user is verified before login, but it's not possible because is necessary log in to change isVerified field from database.

**Comment by morgzz** [comment]
Oh, ok, I understand what your asking now.

To summarize: Validate an anonymous user before the user is created

It's possible to achieve what your seeking, but requires you to make modifications:

To expand on @dsoriano's points, An alternate approach could be:

* Render form `email` text field and submit
* User enters in `email` address and a `token` is generated
* Store the `token` and a hashed value of the user's `email` in a separate entity from the User Entity, and
   then send verification `email` to the user
* When the user clicks the link from `email`
* In your registration controller run logic to validate the `token`
* Purge expired `tokens` if not validated within (2 hours), or once a day, or whatever works for your requirements.
* If the token is valid, purge `token` and then render registration form to user

The other problem I see is you'll need to override the VerifyEmailHelper.php. But it's @finalized so it's not possible.
It would be nice to be able to override the class so you can adjust to your project needs.


@jrushlow Is there any particular reason it's discouraged from being overridden?

**Comment by weaverryan** [comment]
> @jrushlow Is there any particular reason it's discouraged from being overridden?

Things are marked as final on purpose *until* someone comes with a good use-case. That helps us basically have this conversation - and then we can decide of we should remove the `final` or if this new use-case has an even nicer solution :). 

I *am* definitely interested in treating this use-case as a first-class citizen. This means that we could remove `final`, but it's likely that there is a nicer (meaning, something that is even *more* helpful to the user) way of doing this. I would welcome any PR's, even if they're rough - having some code (even if a first draft) makes these conversations 100x easier because we can all look at practical code :)

**Comment by fr43nk** [comment]
@weaverryan please have a look at my merge request #31. 
I build in an optional way for the bundle user to add the email address to the verification url. Honestly I don't see any security issues with that method. If there are any, please explain them to me.

**Comment by adazmy** [comment]
why this bundle doesnt follow the same logic as SymfonyCasts/reset-password-bundle ... or even better... to make them both use the same token requests table.

1. The User fill the registeration form, then he's redirected to a page asking him to check he's email (or a custom route with a flash message) and not logged in until he validates his email
2. UserToken table helps to acheive a [Email Validation Token] => [Email, User]
3. once the email validated, we can auto log in the user... or redirect to login route

i think the idea to keep a UserToken table for managing all those kind of requests is better, specially that anyone can reuse the same logic to do other token verifications with the same table.

**Comment by weaverryan** [comment]
@adazmy It's not a bad idea (I've wondered about this myself). However, verification can be done *without* persistence because you do not need to worry about invalidating a confirmation token (but you do need to do this for reset password requests). We wanted to keep things simpler in this bundle by not using persistence.

But, I hear that people need to be able to allow verification without the user being logged in - I'm going to check #31 for that. It should be easy, we originally just didn't do it for reasons I'll mention there.

Cheers!

**Comment by adazmy** [comment]
@weaverryan thanks for that! 
yep this can let people choose their way (persist or not) and even (invalidate or not if there is a duration param) since it's a matter of config params after the install.
Cheers!

**Comment by weaverryan** [comment]
> persist VS add email on verification URL

i think in #31 we'll add the ability to put the email on the verification URL without the need for persisting. So, you're right... but I still don't see the need to ever persist these verification links :).

Cheers!

**Comment by emancypage** [comment]
I am also waiting for this #31 PR :) It would be great to be able to verify email without being logged in.

**Comment by ocdevops** [comment]
Any update?

**Comment by weaverryan** [comment]
I'm hoping to review, merge, tag soon - sorry, been very busy (as is @jrushlow)

**Comment by lukepass** [comment]
I would like this feature too since in my opinion almost always you would want to login the user only **after** the email verification. Isn't it?

Thanks.

**Comment by AlexandrePetrone** [comment]
@lukepass You're right ! 
It's exactly what i want.

**Comment by lukepass** [comment]
It's a little bit complicated but I completed the verification as I wanted by hand with this code (please note that in my application the `User` is a `Teacher`).

I tried to comment all the critical parts, please let me know if something isn't clear.

`EmailVerifier.php`:

```
public function sendEmailConfirmation(string $verifyEmailRouteName, Teacher $user, TemplatedEmail $email): void
{
    $id = (string) $user->getId();
    $userEmail = $user->getEmail();

    $signatureComponents = $this->verifyEmailHelper->generateSignature(
        $verifyEmailRouteName,
        $id,
        $userEmail
    );

    // appends ID and email to the URL
    $signedUrl = $signatureComponents->getSignedUrl().'&id='.urlencode($id).'&email='.urlencode($userEmail);

    $context = $email->getContext();
    $context['signedUrl'] = $signedUrl;
    $context['expiresAt'] = $signatureComponents->getExpiresAt();

    $email->context($context);

    $this->mailer->send($email);
}

/**
 * @throws VerifyEmailExceptionInterface
 */
public function handleEmailConfirmation(Request $request, Teacher $user): void
{
    // removes all the extra parameters (otherwise it will give an error)
    $uri = preg_replace('/&?(id|email)=[^&]*/', '', $request->getUri());

    $this->verifyEmailHelper->validateEmailConfirmation(
        $uri,
        (string) $user->getId(),
        $user->getEmail()
    );

    $user->setIsVerified(true);

    $this->entityManager->persist($user);
    $this->entityManager->flush();
}
```

`RegistrationController.php`:

```
public function verifyUserEmail(Request $request, GuardAuthenticatorHandler $guardHandler, TeacherLoginFormAuthenticator $authenticator): Response
{
    $id = $request->query->get('id');
    $email = $request->query->get('email');

    // retrieves the user
    $em = $this->getDoctrine()->getManager();
    $user = $em->getRepository(Teacher::class)->findOneBy([
        'id' => intval($id),
        'email' => $email,
    ]);

    // user is not found
    if (!$user) {
        throw $this->createAccessDeniedException();
    }

    // validate email confirmation link, sets User::isVerified=true and persists
    try {
        $this->emailVerifier->handleEmailConfirmation($request, $user);
    } catch (VerifyEmailExceptionInterface $exception) {
        $this->addFlash('verify_email_error', $exception->getReason());

        return $this->redirectToRoute('teacher_register');
    }

    $this->addFlash('success', 'Your success message.');

    // create an authenticated token for the User
    $providerKey = 'teacher'; // firewall name in security.yaml
    $token = $authenticator->createAuthenticatedToken($user, $providerKey);
    // authenticate this in the system
    $guardHandler->authenticateWithToken($token, $request, $providerKey);

    return $this->redirectToRoute('teacher_index');
}
```

Please let me know if you have questions.

**Comment by jrushlow** [comment]
Anonymous validation is currently possible with the VerifyEmailBundle as is. I've created a PR in MakerBundle that will automatically generate the code needed to do this if so desired. Check out https://github.com/symfony/maker-bundle/pull/776
