### ISSUE TITLE
cannot install the bundle

### ISSUE THREAD

**Issue by PiroozMB** [SymfonyCasts/verify-email-bundle#29]
Im getting the following errors on symfony5:

  Problem 1
    - Installation request for symfonycasts/verify-email-bundle ^1.0 -> satisfiable by symfonycasts/verify-email-bundle[v1.0.0].
    - symfonycasts/verify-email-bundle v1.0.0 requires symfony/config ^4.4 | ^5.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

**Comment by jrushlow** [comment]
Hi! Try running `composer show symfony/config` and let me know what the `versions :` it shows installed. 

If `symfony/config` is not installed - try running `composer require symfony/config`. If that fails `composer why-not symfony/config:^5.0` should tell you what package(s) are blocking `symfony/config`

**Comment by PiroozMB** [comment]
Hi thanks for your reply. I get the following:

C:\xampp2\htdocs\my_project_name>composer show symfony/config
name     : symfony/config
descrip. : Symfony Config Component
keywords :
versions : * v3.4.41
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/symfony/config.git cd61db31cbd19cbe4ba9f6968f13c9076e1372ab
dist     : [zip] https://api.github.com/repos/symfony/config/zipball/cd61db31cbd19cbe4ba9f6968f13c9076e1372ab cd61db31cbd19cbe4ba9f6968f13c9076e1372ab
names    : symfony/config

autoload
psr-4
Symfony\Component\Config\ => .
exclude-from-classmap

requires
php ^5.5.9|>=7.0.8
symfony/filesystem ~2.8|~3.0|~4.0
symfony/polyfill-ctype ~1.8

requires (dev)
symfony/dependency-injection ~3.3|~4.0
symfony/event-dispatcher ~3.3|~4.0
symfony/finder ~3.3|~4.0
symfony/yaml ~3.0|~4.0

suggests
symfony/yaml To use the yaml reference dumper

conflicts
symfony/dependency-injection <3.3
symfony/finder <3.3
===================================

C:\xampp2\htdocs\my_project_name>composer why-not symfony/config:^5.0
__root__                       dev-master  requires          symfony/config (3.4.*)
doctrine/doctrine-bundle       1.12.10     requires          symfony/config (^3.4.30|^4.3.3)
sensio/framework-extra-bundle  v5.4.1      requires          symfony/config (^3.4|^4.3)
symfony/framework-bundle       v3.4.41     requires          symfony/config (^3.4.31|^4.3.4)
symfony/security-bundle        v3.4.41     requires          symfony/config (~3.4|~4.0)
symfony/twig-bundle            v3.4.41     requires          symfony/config (~3.2|~4.0)
symfony/web-profiler-bundle    v3.4.41     requires          symfony/config (~3.4|~4.0)
symfony/web-server-bundle      v3.4.41     requires          symfony/config (~3.4|~4.0)
symfony/config                 v5.0.0      conflicts         symfony/finder (<4.4)
symfony/config                 v5.0.0      requires          symfony/filesystem (^4.4|^5.0)
__root__                       dev-master  does not require  symfony/filesystem (but v3.4.41 is installed)
symfony/config                 v5.0.0      requires          symfony/polyfill-ctype (~1.8)
__root__                       dev-master  does not require  symfony/polyfill-ctype (but dev-master is installed)


I don't understand what is causing that.

**Comment by jrushlow** [comment]
It appears that you're running Symfony 3.4. Unfortunately, the `verify-email-bundle` is only compatible with Symfony `4.4` and newer. Have a look at https://symfony.com/doc/current/setup/upgrade_major.html for help in upgrading from Symfony 3.4 to either 4.x or 5.x. 

A word of caution - Symfony 4.x may introduce breaking changes within your code base. I can almost guarantee that upgrading from 3.4 to 5.x will require significant changes to your code base in a standard Symfony App... But it is definitely worth the effort!

**Comment by jrushlow** [comment]
I'm going to close this issue. if you have any questions or need further help, please feel free to re-open it or create a new issue... Thanks!
