### ISSUE TITLE
User can connect without having validated his email

### ISSUE THREAD

**Issue by applicationsweb** [SymfonyCasts/verify-email-bundle#38]
Hello,
When the user registers, he receives a validation email.
I noticed that if he does not click on the validation link he can still connect to his account.
Is this normal and logical behavior?

**Comment by jrushlow** [comment]
Good Morning @applicationsweb , by "connect to his account." I assume you mean that a user still has the ability to login. If so, this is functioning as intended and designed. We're working on adding anonymous validation to the bundle directly and/or indirectly via Symfony's Maker Bundle. 

For progress on this feature, check out issue #27 and PR #31

**Comment by lukepass** [comment]
@applicationsweb I added here a solution until it's implemented in #31 :+1: 

https://github.com/SymfonyCasts/verify-email-bundle/issues/27#issuecomment-747954726

**Comment by jrushlow** [comment]
Anonymous Validation has been implemented in Symfony's MakerBundle - check out https://github.com/symfony/maker-bundle/pull/776

Thanks for opening this issue @applicationsweb , if you need any further help please don't hesitate to ask. Thanks!
