### ISSUE TITLE
I have a problem with email activation

### ISSUE THREAD

**Issue by dawidomk** [SymfonyCasts/verify-email-bundle#41]
Hello, I have a problem with the link that comes to the email. I click on it from the same browser on the phone and it does not activate the account.

**Comment by dawidomk** [comment]
This problem is not present on the computer.

**Comment by jrushlow** [comment]
Hello @dawidomk - Are you experiencing this problem across different browsers on the phone?

**Comment by jrushlow** [comment]
Closing this issue for now. Feel free to reopen if you are still experiencing issues. Thanks!
