### ISSUE TITLE
The account is not validated

### ISSUE THREAD

**Issue by missna04** [SymfonyCasts/verify-email-bundle#47]
If the user is not logged in, the account is not validated after they click on the link in their email
Why?

**Comment by weaverryan** [comment]
Hi @missna04!

Hmm. I'm not sure. I would add some debugging code inside the controller that handles the link after it's clicked to see what's going on. Normally, the user should at least see some error if things aren't working.

Add some more details about what's going on - including code - and we'll see if we can help.

Cheers!
