### ISSUE TITLE
Problem with  "$email->htmlTemplate('registration/confirmation_email.html.twig');"

### ISSUE THREAD

**Issue by mohammedbchaiker** [SymfonyCasts/verify-email-bundle#51]
Hi I'm relatively new developing in Symfony so I was wondering what I should put in the "confirmation_email.html.twig"?

**Comment by GrandOurs35** [comment]
Hi,
it's a Twig Template (almost like html) that will be your email content body.
You can find it at template/confirmation_email.html.twig and when you open the file, you will see what your email verification will looks like.
You can then customize it to your needs. 
The `{{ signedUrl|raw }}` corresponds to a variable that will be injected into your template.
More about Twig: [](https://twig.symfony.com/)

**Comment by jrushlow** [comment]
Thanks @mohammedbchaiker for using our bundle. You can use the Symfony MakerBundle `php bin/console make:registration-form` command to generate all of the required controllers / templates. I would recommend going this route especially if you're new to Symfony. 

If your Symfony project does not already have MakerBundle installed -> `composer require --dev maker-bundle`. Feel free to ask us for help if you run into problems.
