### ISSUE TITLE
Keep user logged in when clicking verification email

### ISSUE THREAD

**Issue by mcgoode** [SymfonyCasts/verify-email-bundle#59]
If the user clicks the email to verify their account and they are currently logged in, they are signed out. How can we keep the user signed in?

**Comment by jrushlow** [comment]
Howdy @mcgoode - I'm not 100% sure on this, but I believe this is a Symfony "issue". I was just noticing the other day that when I make changes to a user record in persistence on a user who is authenticated - their session is invalidated. Granted I was in `dev` manually manipulating a users roles when I noticed this. 

I'm not entirely sure if this would be considered a bug or not. I don't recall this behavior in earlier versions of Symfony but I could be mistaken.

On the positive side, usually when a user validates their email - there is some sort "change" to the users experience. E.g. a user who doesn't have a validated email can't access part of a dashboard. Or something of that nature. In the current behavior, we don't have to invalidate the session as its done for us.

Again, I have not really looked into this behavior at depth, but I'll look into it. If someone else has any input - it would be very much appreciated! Thanks

**Comment by mcgoode** [comment]
@jrushlow thanks for the fast response, I am glad you don't mind digging in. As I recall my users would stay authenticated when clicking on the verification link at some point but something changed. I just have to get things back in order before I can dive any deeper.

**Comment by jrushlow** [comment]
I should also note that in the bundle itself, we do not have any logic that even touches the session or authentication. The bundle simply compares 2 hashed values when you get down to it. And in MakerBundle, we do not generate code (`make:registration`) that deals with user sessions either in regards to email verification IIRC.

**Comment by jrushlow** [comment]
note to self: possibly related to https://github.com/symfony/symfony/pull/38616

**Comment by mcgoode** [comment]
I am on Symfony 4.4, i keep sessions in the DB due to having a load balancer.

On my localhost I can open one tab, authenticate then open a new tab and day go to 127.0.0.1/orders and my session still continues and works. However when I click on the link in the email, I lose the session from all tabs.

https://127.0.0.1:8000/verify/email?expires=1613580598&id=22&signature=UbPuJ7bx7sefD3Jgd4UlMWS%2FGrWct47di7cDxdbEw9k%3D&token=PqfR%2BW2tDV2viIN%2BP%2BSifliBcBSMnIOY3OWJJPozILU%3D

**Comment by mcgoode** [comment]
Figured it out.... well it was nothing to do with this bundle. When I configured `session.cookie_samesite` to `strict` it failed. I set it to `lax` per the documentation. 

https://symfony.com/doc/4.4/reference/configuration/framework.html#cookie-samesite
