### ISSUE TITLE
Link in email is HTTP not HTTPS

### ISSUE THREAD

**Issue by mcgoode** [SymfonyCasts/verify-email-bundle#61]
The URL in the email link is HTTP which we have set Apache to redirect to HTTPS.

IF the user is logged in already, clicks the link in the email,  it wants them to login again. Is there a way I have have the signedURL include the HTTPS?

**Comment by jrushlow** [comment]
hi @mcgoode can you give the solution in https://github.com/SymfonyCasts/verify-email-bundle/issues/49 a try? i believe that may be the issue. If it does not, please let me know.. thanks!

**Comment by mcgoode** [comment]
Im on Symfony 4.4 and all instances are behind a Load Balancer. The LB has the SSL all instances behind the LB are on port 80. 
That option doesnt seem to exist on 4.4 https://symfony.com/doc/4.4/routing.html

```
Unrecognized option "default_uri" under "framework.router". Available options are "enabled", "http_port", "https_port", "resource", "strict_requirements", "type", "utf8".
```

**Comment by mcgoode** [comment]
Maybe a solution here would be to do the anonymous validation.

**Comment by mcgoode** [comment]
anonymous validation did work, but this is a infrastructure issue, however would be nice to have some control over the URL.

**Comment by stingus** [comment]
On Symfony 5.3 the `default_uri` solution set by #49 is not working and shouldn't be used when the request context is available. The correct fix is to get the scheme from the upstream proxy, and this can be achieved with the `trusted_proxies` and `trusted_headers` settings in framework.yaml. More info here: https://symfony.com/doc/current/deployment/proxies.html
