### ISSUE TITLE
exception message translations

### ISSUE THREAD

**Issue by mardif** [SymfonyCasts/verify-email-bundle#73]
Hi,

I would like to show the InvalidSignatureException, ExpiredSignatureException and WrongEmailVerifyException error message translated in my language (italian), but I cannot find a way for to do it.
Can you help me?

Thanks

**Comment by souidev** [comment]
up

**Comment by bocharsky-bw** [comment]
This is a good idea IMO 👍  - I'm reopening this issue for now as I'm going to implement it in #103

**Comment by bocharsky-bw** [comment]
Hey guys!

PR #103 was approved and merged! 🎉  Now I created a downstream PR in Maker bundle, see https://github.com/symfony/maker-bundle/pull/1076 - please, give it a try / review that will help to merge it faster :)

Also, we need _your_ help in this bundle to translate those new translation message in #103 to other languages

Cheers!
