### ISSUE TITLE
Unable to render the registration-form after the make:registration-form commande on symfony 4.4

### ISSUE THREAD

**Issue by sybtra** [SymfonyCasts/verify-email-bundle#93]
Hi there,
thanks for this huge bundle!
After answering yes to all questions beside the anonymous id, to which I answered no.
My form does not render until I commente all codes about mailVerifier in my controller.
Please find attached a screenshot of the error page.
![145055757-021829a4-47e5-4570-b39a-7c6cf9008129](https://user-images.githubusercontent.com/72505088/145665602-cdf6c388-ddb9-4848-99af-4fcbc356fc07.png)
Thanks

**Comment by jrushlow** [comment]
Howdy @sybtra - I apologize for the late reply. I believe this has been addressed in MakerBundle previously. If you're still experiencing issues, please let me know and we can revisit this issue.
