### ISSUE TITLE
Not working through Postman (SPA apps)

### ISSUE THREAD

**Issue by hichemfantar** [SymfonyCasts/verify-email-bundle#94]
I tried replicating the same headers and payload format but It's not working,
There are no errors, I just get back the register page but when I check the db there's nothing.
Works fine using the twig template.
![image](https://user-images.githubusercontent.com/34947993/145754006-1a53bcdf-b3de-4f1f-a3e7-70f3e3e68abe.png)
![image](https://user-images.githubusercontent.com/34947993/145754015-d5e3ac3d-0db3-4b6a-8e42-d1a3401d987e.png)
![image](https://user-images.githubusercontent.com/34947993/145754057-81031523-5302-478e-8511-03741baa4751.png)
![image](https://user-images.githubusercontent.com/34947993/145754081-b6ac7a2d-2d2e-4cc4-b178-16fd2d8d3569.png)
![image](https://user-images.githubusercontent.com/34947993/145754099-9c261b55-48c3-4652-9340-798bc3721934.png)
![image](https://user-images.githubusercontent.com/34947993/145754275-e1585af6-5b39-4cfb-886b-5a9029147dde.png)

I tried echoing the roles array and it seems to be reaching the setter of roles but not saving the user to the db.

**Comment by RocksDesireXebec** [comment]
Hi, excuse me for my english's quality but i've fixed this problem in postman by creating a new register controller and the serializer for handling post data

**Comment by hichemfantar** [comment]
@RocksDesireXebec Thanks I solved it by switching to Laravel 😁
