### ISSUE TITLE
Cannot install the bundle on symfony 4.4

### ISSUE THREAD

**Issue by krachleur** [SymfonyCasts/verify-email-bundle#97]
Hi there, 
I'm trying to install verify-email-bundle on symfony 4.4.34 and I'm getting this error:

```
[InvalidArgumentException]                                                                                                              
  Package symfonycasts/verify-email-bundle has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version
```

php -v => PHP 7.2.3 (cli) (built: Mar 22 2018 22:03:09) ( NTS )

Thanks in advance.

**Comment by bocharsky-bw** [comment]
Hey @krachleur , yeah, this bundle requires `php: >=7.2.5`, if you could upgrade your 7.2.3 PHP version at least to 7.2.5 - this should work for you.
