### ISSUE TITLE
I can login even when isVerified field is set to false in db

### ISSUE THREAD

**Issue by quicotte-formation** [SymfonyCasts/verify-email-bundle#99]
Hi,

Steps:

1.  **installing** the bundle **with composer**
2. then **doctine:schema:update -f**
2.  then **make:registration-form** 
3.  then **make:auth** with a login form

When I register, the isVerified field well stays at false, and when I click on the confirmation link, it passes at true in DB
=> this works perfectly

**BUT**

**_I can login even when isVerified field is set to false in db ; )_**

What do I miss por favor ??
BR
Tom.

**Comment by Seb33300** [comment]
You are probably looking for this: https://symfony.com/doc/current/security/user_checkers.html

**Comment by jrushlow** [comment]
Howdy @quicotte-formation 

Yes @Seb33300 is correct, user checkers is one way to prevent unverified users from logging in. The bundle itself does not enforce any kind of authorization scheme - we leave that up to the user to implement. Reason being, some applications may only use verified emails for say marketing purposes, while still allowing unverified users to access their site. Other applications may only allow users who have verified their email to authenticate. 

I hope this helps!
